### ISSUE TITLE
Ground truth

### ISSUE THREAD

**Issue by FarzanehGhorbani** [benedekrozemberczki/LabelPropagation#6]
Hi.thank you for this amazing source code.I use this source code for my college project.
But I need ground truth of this dataset.may you send this to me?please😢😥

**Comment by benedekrozemberczki** [comment]
https://snap.stanford.edu/data/gemsec-Facebook.html

**Comment by FarzanehGhorbani** [comment]
Thank you so much. 💓

**Comment by benedekrozemberczki** [comment]
Can you star the repo and hit follow?

**Comment by FarzanehGhorbani** [comment]
Yes, I can.
